// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHNnqtcTjMrDCCQvYaKq5V57iI31h1ptk',
    appId: '1:515087594310:web:28255aca1bc92e3d8bab47',
    messagingSenderId: '515087594310',
    projectId: 'lost-treasures-d4a3c',  
    authDomain: 'lost-treasures-d4a3c.firebaseapp.com',
    storageBucket: 'lost-treasures-d4a3c.firebasestorage.app', 
  );


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDosNj0XxNsytuBNZvkMTxcR8nZFKn53lI',
    appId: '1:515087594310:android:dcded3663c94c4f38bab47',
    messagingSenderId: '515087594310',
    projectId: 'lost-treasures-d4a3c',
    storageBucket: 'lost-treasures-d4a3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgqnbDaZo5upOHj2HCHQspLxbg8VKjQXU',
    appId: '1:515087594310:ios:6977ae64c5acb6238bab47',
    messagingSenderId: '515087594310',
    projectId: 'lost-treasures-d4a3c',
    storageBucket: 'lost-treasures-d4a3c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgqnbDaZo5upOHj2HCHQspLxbg8VKjQXU',
    appId: '1:515087594310:ios:6977ae64c5acb6238bab47',
    messagingSenderId: '515087594310',
    projectId: 'lost-treasures-d4a3c',
    storageBucket: 'lost-treasures-d4a3c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHNnqtcTjMrDCCQvYaKq5V57iI31h1ptk',
    appId: '1:515087594310:web:c6fafc9ca0284d958bab47',
    messagingSenderId: '515087594310',
    projectId: 'lost-treasures-d4a3c',
    authDomain: 'lost-treasures-d4a3c.firebaseapp.com',
    storageBucket: 'lost-treasures-d4a3c.firebasestorage.app',
  );
}
